server:
  port: 8089
spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOSTNAME:localhost}:${DATABASE_PORT:5435}/postgres
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 3
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false